import { BaseTexture } from "../../../resource/BaseTexture";
import { Vector4 } from "../../math/Vector4";
import { BaseMaterial } from "./BaseMaterial";
export declare class EffectMaterial extends BaseMaterial {
    static RENDERMODE_ADDTIVE: number;
    static RENDERMODE_ALPHABLENDED: number;
    static defaultMaterial: EffectMaterial;
    static SHADERDEFINE_MAINTEXTURE: number;
    static SHADERDEFINE_TILINGOFFSET: number;
    static SHADERDEFINE_ADDTIVEFOG: number;
    static MAINTEXTURE: number;
    static TINTCOLOR: number;
    static TILINGOFFSET: number;
    static CULL: number;
    static BLEND: number;
    static BLEND_SRC: number;
    static BLEND_DST: number;
    static DEPTH_TEST: number;
    static DEPTH_WRITE: number;
    private _color;
    renderMode: number;
    colorR: number;
    colorG: number;
    colorB: number;
    colorA: number;
    color: Vector4;
    texture: BaseTexture;
    tilingOffsetX: number;
    tilingOffsetY: number;
    tilingOffsetZ: number;
    tilingOffsetW: number;
    tilingOffset: Vector4;
    depthWrite: boolean;
    cull: number;
    blend: number;
    blendSrc: number;
    blendDst: number;
    depthTest: number;
    constructor();
    clone(): any;
}
