import { Widget } from "./Widget";
import { Node } from "../display/Node";
import { Sprite } from "../display/Sprite";
export declare class UIComponent extends Sprite {
    protected _anchorX: number;
    protected _anchorY: number;
    protected _dataSource: any;
    protected _toolTip: any;
    protected _tag: any;
    protected _disabled: boolean;
    protected _gray: boolean;
    protected _widget: Widget;
    constructor();
    destroy(destroyChild?: boolean): void;
    width: number;
    get_width(): number;
    protected measureWidth(): number;
    height: number;
    get_height(): number;
    protected measureHeight(): number;
    dataSource: any;
    get_dataSource(): any;
    set_dataSource(value: any): void;
    top: number;
    get_top(): number;
    set_top(value: number): void;
    bottom: number;
    get_bottom(): number;
    set_bottom(value: number): void;
    left: number;
    right: number;
    centerX: number;
    centerY: number;
    protected _sizeChanged(): void;
    toolTip: any;
    private onMouseOver;
    private onMouseOut;
    gray: boolean;
    disabled: boolean;
    private _getWidget;
    scaleX: number;
    set_scaleX(value: number): void;
    scaleY: number;
    set_scaleY(value: number): void;
    protected onCompResize(): void;
    set_width(value: number): void;
    set_height(value: number): void;
    anchorX: number;
    get_anchorX(): number;
    set_anchorX(value: number): void;
    anchorY: number;
    get_anchorY(): number;
    set_anchorY(value: number): void;
    protected _childChanged(child?: Node): void;
}
