import { HTMLCanvas } from "../resource/HTMLCanvas";
export declare class Browser {
    static userAgent: string;
    static onMobile: boolean;
    static onIOS: boolean;
    static onMac: boolean;
    static onIPhone: boolean;
    static onIPad: boolean;
    static onAndroid: boolean;
    static onWP: boolean;
    static onQQBrowser: boolean;
    static onMQQBrowser: boolean;
    static onSafari: boolean;
    static onIE: boolean;
    static onWeiXin: boolean;
    static onPC: boolean;
    static onMiniGame: boolean;
    static onBDMiniGame: boolean;
    static onKGMiniGame: boolean;
    static onQGMiniGame: boolean;
    static onVVMiniGame: boolean;
    static onFirefox: boolean;
    static onEdge: boolean;
    static onLayaRuntime: boolean;
    static supportWebAudio: boolean;
    static supportLocalStorage: boolean;
    static canvas: HTMLCanvas;
    static context: CanvasRenderingContext2D;
    private static _window;
    private static _document;
    private static _container;
    private static _pixelRatio;
    static mainCanvas: any;
    private static hanzi;
    private static fontMap;
    static measureText: Function;
    static createElement(type: string): any;
    static getElementById(type: string): any;
    static removeElement(ele: any): void;
    static now(): number;
    static readonly clientWidth: number;
    static readonly clientHeight: number;
    static readonly width: number;
    static readonly height: number;
    static readonly pixelRatio: number;
    static container: any;
    static readonly window: any;
    static readonly document: any;
}
