import { Sprite } from "../display/Sprite";
import { Stage } from "../display/Stage";
import { Rectangle } from "../maths/Rectangle";
export declare class Utils {
    static gStage: Stage;
    private static _gid;
    private static _pi;
    private static _pi2;
    protected static _extReg: RegExp;
    static toRadian(angle: number): number;
    static toAngle(radian: number): number;
    static toHexColor(color: number): string;
    static getGID(): number;
    static parseXMLFromString: Function;
    static concatArray(source: any[], array: any[]): any[];
    static clearArray(array: any[]): any[];
    static copyArray(source: any[], array: any[]): any[];
    static getGlobalRecByPoints(sprite: Sprite, x0: number, y0: number, x1: number, y1: number): Rectangle;
    static getGlobalPosAndScale(sprite: Sprite): Rectangle;
    static bind(fun: Function, scope: any): Function;
    static updateOrder(array: any[]): boolean;
    static transPointList(points: any[], x: number, y: number): void;
    static parseInt(str: string, radix?: number): number;
    static getFileExtension(path: string): string;
    static getTransformRelativeToWindow(coordinateSpace: Sprite, x: number, y: number): any;
    static fitDOMElementInArea(dom: any, coordinateSpace: Sprite, x: number, y: number, width: number, height: number): void;
    static isOkTextureList(textureList: any[]): boolean;
    static isOKCmdList(cmds: any[]): boolean;
    static getQueryString(name: string): string;
}
