import { Bone } from "./Bone";
import { AnimationTemplet } from "../AnimationTemplet";
import { SkinSlotDisplayData } from "./SkinSlotDisplayData";
import { Texture } from "../../resource/Texture";
import { Matrix } from "../../maths/Matrix";
import { Graphics } from "../../display/Graphics";
import { Skeleton } from "./Skeleton";
export declare class Templet extends AnimationTemplet {
    private _mainTexture;
    private _graphicsCache;
    srcBoneMatrixArr: any[];
    ikArr: any[];
    tfArr: any[];
    pathArr: any[];
    boneSlotDic: any;
    bindBoneBoneSlotDic: any;
    boneSlotArray: any[];
    skinDataArray: any[];
    skinDic: any;
    subTextureDic: any;
    isParseFail: boolean;
    yReverseMatrix: Matrix;
    drawOrderAniArr: any[];
    eventAniArr: any[];
    attachmentNames: any[];
    deformAniArr: any[];
    skinSlotDisplayDataArr: SkinSlotDisplayData[];
    private _isParseAudio;
    private _isDestroyed;
    private _rate;
    isParserComplete: boolean;
    aniSectionDic: any;
    private _skBufferUrl;
    private _textureDic;
    private _loadList;
    private _path;
    private _relativeUrl;
    tMatrixDataLen: number;
    mRootBone: Bone;
    mBoneArr: Bone[];
    loadAni(url: string): void;
    private onComplete;
    parseData(texture: Texture, skeletonData: ArrayBuffer, playbackRate?: number): void;
    buildArmature(aniMode?: number): Skeleton;
    parse(data: ArrayBuffer): void;
    private _parseTexturePath;
    private _textureComplete;
    private _parsePublicExtData;
    getTexture(name: string): Texture;
    showSkinByIndex(boneSlotDic: any, skinIndex: number, freshDisplayIndex?: boolean): boolean;
    getSkinIndexByName(skinName: string): number;
    getGrahicsDataWithCache(aniIndex: number, frameIndex: number): Graphics;
    setGrahicsDataWithCache(aniIndex: number, frameIndex: number, graphics: Graphics): void;
    deleteAniData(aniIndex: number): void;
    destroy(): void;
    getAniNameByIndex(index: number): string;
    rate: number;
}
