export class LayaGL {
}
LayaGL.ARRAY_BUFFER_TYPE_DATA = 0;
LayaGL.ARRAY_BUFFER_TYPE_CMD = 1;
LayaGL.ARRAY_BUFFER_REF_REFERENCE = 0;
LayaGL.ARRAY_BUFFER_REF_COPY = 1;
LayaGL.UPLOAD_SHADER_UNIFORM_TYPE_ID = 0;
LayaGL.UPLOAD_SHADER_UNIFORM_TYPE_DATA = 1;
