import { GradientDataNumber } from "./GradientDataNumber";
import { IClone } from "../../IClone";
import { Vector3 } from "../../../math/Vector3";
export declare class GradientSize implements IClone {
    static createByGradient(gradient: GradientDataNumber): GradientSize;
    static createByGradientSeparate(gradientX: GradientDataNumber, gradientY: GradientDataNumber, gradientZ: GradientDataNumber): GradientSize;
    static createByRandomTwoConstant(constantMin: number, constantMax: number): GradientSize;
    static createByRandomTwoConstantSeparate(constantMinSeparate: Vector3, constantMaxSeparate: Vector3): GradientSize;
    static createByRandomTwoGradient(gradientMin: GradientDataNumber, gradientMax: GradientDataNumber): GradientSize;
    static createByRandomTwoGradientSeparate(gradientXMin: GradientDataNumber, gradientXMax: GradientDataNumber, gradientYMin: GradientDataNumber, gradientYMax: GradientDataNumber, gradientZMin: GradientDataNumber, gradientZMax: GradientDataNumber): GradientSize;
    private _type;
    private _separateAxes;
    private _gradient;
    private _gradientX;
    private _gradientY;
    private _gradientZ;
    private _constantMin;
    private _constantMax;
    private _constantMinSeparate;
    private _constantMaxSeparate;
    private _gradientMin;
    private _gradientMax;
    private _gradientXMin;
    private _gradientXMax;
    private _gradientYMin;
    private _gradientYMax;
    private _gradientZMin;
    private _gradientZMax;
    readonly type: number;
    readonly separateAxes: boolean;
    readonly gradient: GradientDataNumber;
    readonly gradientX: GradientDataNumber;
    readonly gradientY: GradientDataNumber;
    readonly gradientZ: GradientDataNumber;
    readonly constantMin: number;
    readonly constantMax: number;
    readonly constantMinSeparate: Vector3;
    readonly constantMaxSeparate: Vector3;
    readonly gradientMin: GradientDataNumber;
    readonly gradientMax: GradientDataNumber;
    readonly gradientXMin: GradientDataNumber;
    readonly gradientXMax: GradientDataNumber;
    readonly gradientYMin: GradientDataNumber;
    readonly gradientYMax: GradientDataNumber;
    readonly gradientZMin: GradientDataNumber;
    readonly gradientZMax: GradientDataNumber;
    constructor();
    getMaxSizeInGradient(): number;
    cloneTo(destObject: any): void;
    clone(): any;
}
