import { BaseMaterial } from "laya/d3/core/material/BaseMaterial";
import { Vector4 } from "laya/d3/math/Vector4";
import { ShaderDefines } from "laya/d3/shader/ShaderDefines";
import { BaseTexture } from "laya/resource/BaseTexture";
export declare class CartoonMaterial extends BaseMaterial {
    static ALBEDOTEXTURE: number;
    static BLENDTEXTURE: number;
    static OUTLINETEXTURE: number;
    static SHADOWCOLOR: number;
    static SHADOWRANGE: number;
    static SHADOWINTENSITY: number;
    static SPECULARRANGE: number;
    static SPECULARINTENSITY: number;
    static OUTLINEWIDTH: number;
    static OUTLINELIGHTNESS: number;
    static TILINGOFFSET: number;
    static SHADERDEFINE_ALBEDOTEXTURE: number;
    static SHADERDEFINE_BLENDTEXTURE: number;
    static SHADERDEFINE_OUTLINETEXTURE: number;
    static SHADERDEFINE_TILINGOFFSET: number;
    static shaderDefines: ShaderDefines;
    static __init__(): void;
    static initShader(): void;
    albedoTexture: BaseTexture;
    blendTexture: BaseTexture;
    outlineTexture: BaseTexture;
    shadowColor: Vector4;
    shadowRange: number;
    shadowIntensity: number;
    specularRange: number;
    specularIntensity: number;
    outlineWidth: number;
    outlineLightness: number;
    tilingOffset: Vector4;
    constructor();
    clone(): any;
}
