import { Sprite } from "./laya/display/Sprite";
import { Stage } from "./laya/display/Stage";
import { LoaderManager } from "./laya/net/LoaderManager";
import { Render } from "./laya/renders/Render";
import { Timer } from "./laya/utils/Timer";
export declare class Laya {
    static stage: Stage;
    static systemTimer: Timer;
    static startTimer: Timer;
    static physicsTimer: Timer;
    static updateTimer: Timer;
    static lateTimer: Timer;
    static timer: Timer;
    static loader: LoaderManager;
    static version: string;
    static render: Render;
    static _currentStage: Sprite;
    private static _isinit;
    static isWXOpenDataContext: boolean;
    static isWXPosMsg: boolean;
    static __init(_classs: any): void;
    static init(width: number, height: number, ...plugins: any[]): any;
    static _getUrlPath(): string;
    static _arrayBufferSlice(start: number, end: number): ArrayBuffer;
    static alertGlobalError: boolean;
    private static _evcode;
    static _runScript(script: string): any;
    static enableDebugPanel(debugJsPath?: string): void;
    private static isNativeRender_enable;
    private static enableNative;
}
export declare var __init: typeof Laya.__init;
export declare var init: typeof Laya.init;
export declare var stage: any;
export declare var systemTimer: any;
export declare var startTimer: any;
export declare var physicsTimer: any;
export declare var updateTimer: any;
export declare var lateTimer: any;
export declare var timer: any;
export declare var loader: any;
export declare var version: any;
export declare var render: any;
export declare var isWXOpenDataContext: any;
export declare var isWXPosMsg: any;
export declare var alertGlobalError: boolean;
export declare var enableDebugPanel: typeof Laya.enableDebugPanel;
